<html>
     <STYLE type="text/css">
        body {
            font:normal 100% Calibri,Arial,Helvetica;
            color:#000000;
        }
        table tr td, table tr th {
            font-size: 90%;
        }
        table.details tr th{
            font-weight: bold;
            text-align:left;
            background: #a6caf0;
        }
        table.details tr td{
            background: #eeeee0;
        }
        p {
            line-height:1.5em;
            margin-top:0.5em; margin-bottom:1.0em;
        }
        h1 {
            margin: 0px 0px 5px; font: bold 188% Calibri,Arial,Helvetica
        }
        h2 {
            margin-top: 1em; margin-bottom: 0.5em; font: bold 125% Calibri,Arial,Helvetica
        }
        .Error {
             font-weight:bold; color: red;
        }
        .Failure {
             font-weight:bold; color: red;
        }
		.Pass {
             font-weight:bold; color: green;
        }
        .Properties {
             text-align:right;
        }
   </STYLE>
<body>
	<h1><img src="cid:logo"/>&nbsp;&nbsp;<font color="#005990">{{reportTitle}}</font></h1>
      <table width="100%">
        <tr>
            <td align="left"></td><td align="right">Generated by IF Auto Test Framework</td>
        </tr>
      </table>
      <hr size="1">
	  {% if envInfo!={} %}
	  <h2>Test Environment:</h2>
	  	 <table class="details" border="0", cellpadding="5" cellspacing="2" width="60%">
	       <tr>
		     <th colspan="2">Environment Information:</td>
		   </tr>
		   {% for keyName in envInfo %}
		   <tr class="Pass"><td>{{keyName}}</td><td>{{envInfo[keyName]}}</td></tr>
		   {% endfor %}
	     </table>
	  {% endif %}
    
	<h2>Test Summary:</h2>
     <table class="details" border="0" cellpadding="5" cellspacing="2" width="45%">
		 <tr valign="middle">
		     <th>Tests</th><th>Passes</th><th>Failures</th><th>Errors</th><th>Skips</th><th>Passrate</th><th>Execution time(seconds)</th>
	     </tr>
		 <tr valign="middle" class="Pass">
             <td>{{filteredData.summaryInfo['tests']}}</td><td>{{filteredData.summaryInfo['passes']}}</td><td {%if filteredData.summaryInfo['failures']!=0%}class="Failure"{% endif %}>{{filteredData.summaryInfo['failures']}}</td><td {%if filteredData.summaryInfo['errors']!=0%}class="Failure"{% endif %}>{{filteredData.summaryInfo['errors']}}</td><td>{{filteredData.summaryInfo['skips']}}</td><td>{{filteredData.summaryInfo['passrate']}}%</td><td>{{filteredData.summaryInfo['time']}}</td>
		 </tr>
	  </table>
	
	{% if filteredData.testSuitesInfo!={} %}
	<h2>Test Details:</h2>
     <table class="details" border="0" cellpadding="5" cellspacing="2" width="95%">
	     <tr valign="middle">
             <th width="70%">Suite Name</th><th>Tests</th><th>Passes</th><th>Failures</th><th>Errors</th><th>Skips</th>
         </tr>
         {% for suiteName in filteredData.testSuitesInfo %}
         <tr valign="middle" class="Pass">
             <td>{{suiteName}}</td><td>{{filteredData.testSuitesInfo[suiteName]['T']}}</td><td>{{filteredData.testSuitesInfo[suiteName]['P']}}</td><td {% if filteredData.testSuitesInfo[suiteName]['F']!=0 %}class="Failure"{% endif %}>{{filteredData.testSuitesInfo[suiteName]['F']}}</td><td {% if filteredData.testSuitesInfo[suiteName]['E']!=0 %}class="Failure"{% endif %}>{{filteredData.testSuitesInfo[suiteName]['E']}}</td><td>{{filteredData.testSuitesInfo[suiteName]['S']}}</td>
         </tr>
         {% endfor %}
     </table>
	 {% endif %}

	 {% if (filteredData.failureCasesInfo!={}) or (filteredData.errorCasesInfo!={}) %}
     <h2>Automation Charts:</h2>
     <img src="cid:failureBySuites" />&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<img src="cid:failureByPriorities"/>
	 {% endif %}
	
	 {% if filteredData.failureCasesInfo!={} %}
	 <h2>Failed Tests List:</h2>
	  <table class="details" border="0" cellpadding="5" cellspacing="2" width="90%">
	     <tr valign="middle"><th>Method Name</th><th width="70%" >Title</th><th>Priority</th><th>Suite Name</th></tr>
		 {% for methodName in filteredData.failureCasesInfo %}
	     <tr valign="middle" class="Failure">
	                        <td>{{methodName}}</td><td>{{filteredData.failureCasesInfo[methodName]['name']}}</td><td>{{filteredData.failureCasesInfo[methodName]['priority']}}</td><td>{{filteredData.failureCasesInfo[methodName]['classname']}}</td>
	     </tr>
		 {% endfor %}
	  </table>
	 {% endif %}
	 
	 {% if filteredData.errorCasesInfo!={} %}
	 <h2>Error Tests List:</h2>
	   <table class="details" border="0" cellpadding="5" cellspacing="2" width="90%">
	      <tr valign="top"><th>Method Name</th><th width="70%" >Title</th><th>Priority</th><th>Suite Name</th></tr>
	      {% for methodName in filteredData.errorCasesInfo %}
          <tr valign="top" class="Failure">
		  <td>{{methodName}}</td><td>{{filteredData.errorCasesInfo[methodName]['name']}}</td><td>{{filteredData.errorCasesInfo[methodName]['priority']}}</td><td>{{filteredData.errorCasesInfo[methodName]['classname']}}</td>
          </tr>
		  {% endfor %}
	  </table>
	 {% endif %}
	
	<p></p><p></p><p>You can also check attached JUnit report for more details. If you have any questions, please feel free to contact to us!</p>
    <p>
	Thanks,<br>
	Integration framework QA Team
</body>
</html>